version: "3"

services:
    mysqld:
        image: mysql:latest
        container_name: hospital-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hospital
            MYSQL_PORT: "3306"
        volumes:
            - mysql-data:/var/lib/mysql

    e-health-app:
        image: malise/hospital:latest
        ports:
            - "8081:8081"
        depends_on:
            - mysqld
        environment:
            MYSQL_HOST: mysqld

volumes:
    mysql-data:
