---
- name: Run Docker Compose
  hosts: all
  become: true
  tasks:
      - name: Create file
        copy:
            content: Create \n
            dest: /tmp/test.txt

      - name: Increase no. of open files
        sysctl:
            name: fs.file-max
            value: "500000"
            state: present
        become: true

      # Installing necessary packages before installing Docker
      - name: Install required system packages
        apt:
            name: "{{ item }}"
            state: latest
            update_cache: yes
        loop:
            - "apt-transport-https"
            - "ca-certificates"
            - "curl"
            - "software-properties-common"
            - "python3-pip"
            - "virtualenv"
            - "python3-setuptools"
        become: true

      - name: Add Docker GPG apt Key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        become: true

      - name: Add Docker Repository
        apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
            state: present
        become: true

      - name: Install Docker and Docker-Compose
        apt:
            pkg:
                - docker
                - docker-ce
                - docker-compose
            state: latest
            update_cache: yes
        become: true

      - name: Running Docker without root and add it to user groups
        shell: |
            usermod -aG docker $USER
        become: true

      - name: Recursive change ownership
        file:
            path: /home/kudez/Hospital
            state: directory
            recurse: yes
            owner: kudez
        become: true

      - name: Copy Docker Compose file
        copy:
            src: /home/kudez/Engineer/java/e-health-app/docker-compose.yml # path on my local machine
            dest: /home/kudez/Hospital/docker-compose.yml # Replace with the destination path on the remote server
            owner: kudez
            group: kudez
            mode: 0755 # Adjust the file permissions as needed
        become: true

      - name: Start Docker Compose
        command: docker-compose -f /home/kudez/Hospital/docker-compose.yml up -d
