apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-health-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-health-app
  template:
    metadata:
      labels:
        app: e-health-app
    spec:
      containers:
      - name: e-health-app
        image: malise/hospital:v1
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_HOST
          value: mysqld
        readinessProbe:
          httpGet:
            path: /e-health-app/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
