apiVersion: v1
kind: Service
metadata:
  name: e-health-app-service
spec:
  selector:
    app: e-health-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31000
  type: NodePort # want to access the service from outside the cluster
