apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64-encoded value for "root"
  MYSQL_DATABASE: aG9zcGl0YWw= # base64-encoded value for "hospital"
