version: 2.1

jobs:
    build:
        docker:
            - image: openjdk:17.0
        steps:
            - checkout
            - run:
                  name: Build and Test
                  command: mvn clean install
            - persist_to_workspace:
                  root: /workspace
                  paths:
                      - target/e-health-app.war

    # deploy:
    #     docker:
    #         - image: tomcat:9.0-jre11
    #     steps:
    #         - attach_workspace:
    #               at: /workspace
    #         - run:
    #               name: Deploy to Tomcat
    #               command: cp /workspace/target/e-health-app.war /usr/local/tomcat/webapps/

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
