version: 2.1

jobs:
  build:
    docker:
    - image: maven:3.8.3-jdk-11
    working_directory: ~/app

    steps:
    - checkout

    - run:
        name: Build with Maven
        command: mvn -B package --file pom.xml

    - setup_remote_docker

    - run:
        name: Build & push Docker image
        command: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t malise/hospital .
          docker tag malise/hospital:latest
          docker push malise/hospital:latest

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only:
            - main

