apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-driver-configmap
data:
  mysql-connector-java.jar: |-
{{ printf "    " }}{{- with .Files.Get "/home/kudez/Engineer/java/e-health-app/mysql-connector-j-8.2.0.jar" -}}
{{ .AsSecrets | indent 4 }}
{{- end }}
